package com.timmitof.hometask

import com.timmitof.hometask.models.ModelClass

abstract class Constants {
    companion object{
        val array = arrayListOf(
            ModelClass(
                R.drawable.image,
                "Name",
                "Description",
            "DetailDescription"
            ),
            ModelClass(
                R.drawable.image,
                "Name",
                "Description",
            "DetailDescription"
            ),
            ModelClass(
                R.drawable.image,
                "Name",
                "Description",
            "DetailDescription"
            ),
            ModelClass(
                R.drawable.image,
                "Name",
                "Description",
            "DetailDescription"
            ),
            ModelClass(
                R.drawable.image,
                "Name",
                "Description",
            "DetailDescription"
            ),
            ModelClass(
                R.drawable.image,
                "Name",
                "Description",
            "DetailDescription"
            ),
            ModelClass(
                R.drawable.image,
                "Name",
                "Description",
            "DetailDescription"
            ),
            ModelClass(
                R.drawable.image,
                "Name",
                "Description",
            "DetailDescription"
            ),
            ModelClass(
                R.drawable.image,
                "Name",
                "Description",
            "DetailDescription"
            ),
            ModelClass(
                R.drawable.image,
                "Name",
                "Description",
            "DetailDescription"
            ),
            ModelClass(
                R.drawable.image,
                "Name",
                "Description",
            "DetailDescription"
            ),
            ModelClass(
                R.drawable.image,
                "Name",
                "Description",
            "DetailDescription"
            ),
            ModelClass(
                R.drawable.image,
                "Name",
                "Description",
            "DetailDescription"
            ),

        )
    }
}